<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanTxtWrongCompanyId</name>
   <tag></tag>
   <elementGuidId>b3d98807-32d6-429c-812b-1557b98df77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.form__error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>567fb9e5-e7a1-4f3d-97e2-932aeaf1738c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__error</value>
      <webElementGuid>f16aa119-2215-4999-924a-1a35bb4abbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Perusahaan tidak terdaftar.</value>
      <webElementGuid>cc435dc0-fd56-418c-9ed9-121d2b77b465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;container is-login&quot;]/div[@class=&quot;form__container&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;form__group has-icon has-error&quot;]/span[@class=&quot;form__error&quot;]</value>
      <webElementGuid>c307f4f6-b37d-473c-8a0e-eb5e59329d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::span[3]</value>
      <webElementGuid>32d8a3a7-ff83-4486-85d0-5d870e4d93a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik Disini'])[1]/preceding::span[3]</value>
      <webElementGuid>35dd4e71-7b74-4494-975a-f4162cb1a61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama Perusahaan tidak terdaftar.']/parent::*</value>
      <webElementGuid>868aa2b3-74c6-45fc-94bb-388e7f3ecd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>61519139-c75b-41bb-9b45-c9285279b4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nama Perusahaan tidak terdaftar.' or . = 'Nama Perusahaan tidak terdaftar.')]</value>
      <webElementGuid>b24d0cad-f7d7-434c-bcb0-7c023a303443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
