<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanTxtProfileName</name>
   <tag></tag>
   <elementGuidId>3d061f8a-28f6-455f-bfd1-d4b4cac1fef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a-profile']/div/div[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6 > span > span.nav-profile-outlet-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0af2f38d-3595-47fe-b58b-9b1291ca7ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-profile-outlet-name</value>
      <webElementGuid>7a808a83-a1ed-41fc-9863-782b44b23087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NB</value>
      <webElementGuid>6d146c53-598d-4c1c-b536-b61759af4465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-profile&quot;)/div[1]/div[@class=&quot;col-sm-6&quot;]/span[1]/span[@class=&quot;nav-profile-outlet-name&quot;]</value>
      <webElementGuid>1231d371-aad6-44a2-b22d-c65f843bfde5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-profile']/div/div[2]/span/span</value>
      <webElementGuid>31704d1e-92fd-44b5-b7dc-95e7ee16e4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NB'])[1]/following::span[5]</value>
      <webElementGuid>bb233b25-dd4f-42e8-a0ba-d821ad302227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::span[9]</value>
      <webElementGuid>1712422f-2b1a-46db-a83b-044b3b321a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Top Up Rp 10.000'])[1]/preceding::span[1]</value>
      <webElementGuid>a9ff81f9-c567-4b5f-bed7-b71cbbbac10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet Saya'])[1]/preceding::span[3]</value>
      <webElementGuid>2b225124-de0d-4194-9a5a-573b90564ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span</value>
      <webElementGuid>5c9bd52a-1086-46a7-aea4-2a1f0efb0e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NB' or . = 'NB')]</value>
      <webElementGuid>e9cfad16-30d8-42ca-8c5e-f9cc4c9445ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
