<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanTxtProfileName</name>
   <tag></tag>
   <elementGuidId>60b02a31-8345-47b7-a35a-5ed26a5bead0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdown-profile']/a/span[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.nav-profile-outlet-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>933d8fb4-1478-4b3d-9daf-d47645143f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-profile-outlet-name</value>
      <webElementGuid>0115c988-ff9e-444b-b0f3-31c1390ec68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NB</value>
      <webElementGuid>47cfaa72-bfcf-4ec8-8ec0-10de13fbcc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-profile&quot;)/a[@class=&quot;clearfix waves-effect waves-block no-bg-hover a-profile&quot;]/span[2]/span[@class=&quot;user-info&quot;]/span[@class=&quot;nav-profile-outlet-name&quot;]</value>
      <webElementGuid>d2dc8a0c-82d0-44b0-8999-2a51a670aa73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-profile']/a/span[2]/span/span</value>
      <webElementGuid>23c5d3fd-f6dc-4d14-a702-0b8492f53acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::span[4]</value>
      <webElementGuid>fb17fe37-bfcd-4720-9f5c-be70c9de8fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::span[5]</value>
      <webElementGuid>5ef5fc1d-3bf1-436c-818a-853c66b9a47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NB'])[2]/preceding::span[4]</value>
      <webElementGuid>e644dce1-8068-4ce7-9f48-949f7b739491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Top Up Rp 10.000'])[1]/preceding::span[5]</value>
      <webElementGuid>5bed5e8d-fe2c-46d8-bced-e45dc5763e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NB']/parent::*</value>
      <webElementGuid>1ad4342b-7e0d-4471-8d4d-9b3133737b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span</value>
      <webElementGuid>a6ec225c-c0fa-45df-97ac-0fbf9852bfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NB' or . = 'NB')]</value>
      <webElementGuid>fbd8dab5-b8e0-4958-b9ab-f34a66196d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
